# Pages placed under these sections will be shown on homepage and archive page.
mainSections = ["post"]
# Output page's full content in RSS.
rssFullContent = true
favicon = "/dragon-svgrepo-com.svg"

[footer]
since = 2020
customText = ""

[dateFormat]
published = "Jan 02, 2006"
lastUpdated = "Jan 02, 2006 15:04 MST"

[sidebar]
emoji = "üêß"
subtitle = "Computer Engineer"

[sidebar.avatar]
enabled = true
local = true
src = "img/perfil_linkedin.jpeg"

[article]
headingAnchor = false
math = false
readingTime = false

[article.license]
enabled = true
default = "Licensed under CC BY-NC-SA 4.0"

## Widgets
[[widgets.homepage]]
type = "search"


[colorScheme]
toggle = true
default = "auto"

[imageProcessing.cover]
enabled = true

[imageProcessing.content]
enabled = true